blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/jonathanlinford/oscar/discussions
    about: For usage questions, ideas that aren't fully-baked, or general discussion.
